//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShannonEntropy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShannonEntropy.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de ....
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor permita el acceso.
        /// </summary>
        internal static string AllowAccess {
            get {
                return ResourceManager.GetString("AllowAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo seleccionado sobrepasa los 20 Mbs abrir archivos muy grandes podría causar la interrupción de la aplicación por restricción del sistema operativo o incluso bloquear el dispositivo
        ///¿Continuar?.
        /// </summary>
        internal static string BigFile {
            get {
                return ResourceManager.GetString("BigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcular.
        /// </summary>
        internal static string CalculateEntropy {
            get {
                return ResourceManager.GetString("CalculateEntropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar a ingles.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        internal static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Limpiar texto?.
        /// </summary>
        internal static string CleanTextAsk {
            get {
                return ResourceManager.GetString("CleanTextAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos equiprobables.
        /// </summary>
        internal static string EquiProbable {
            get {
                return ResourceManager.GetString("EquiProbable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error abriendo este archivo, prueba con uno diferente....
        /// </summary>
        internal static string ErrorPickingFile {
            get {
                return ResourceManager.GetString("ErrorPickingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento #1.
        /// </summary>
        internal static string Event1 {
            get {
                return ResourceManager.GetString("Event1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento #2.
        /// </summary>
        internal static string Event2 {
            get {
                return ResourceManager.GetString("Event2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relación frecuencia - entropia.
        /// </summary>
        internal static string FrecuencyEntropy {
            get {
                return ResourceManager.GetString("FrecuencyEntropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La probabilidad de cada evento en relación con la entropia resultante.
        /// </summary>
        internal static string FrecuencyEntropySubtitle {
            get {
                return ResourceManager.GetString("FrecuencyEntropySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropia de una imagen.
        /// </summary>
        internal static string FromPhoto {
            get {
                return ResourceManager.GetString("FromPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una medida de la distribución de probabilidad de los valores de gris.
        /// </summary>
        internal static string FromPhotoSubtitle {
            get {
                return ResourceManager.GetString("FromPhotoSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropia de un texto.
        /// </summary>
        internal static string FromText {
            get {
                return ResourceManager.GetString("FromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representa el número necesario de bits para codificar el mensaje en un codificador óptimo.
        /// </summary>
        internal static string FromTextSubtitle {
            get {
                return ResourceManager.GetString("FromTextSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha denegado el acceso a su camera, por favor permita el acceso desde ajustes de su dispositivo.
        /// </summary>
        internal static string HasDeniedCamera {
            get {
                return ResourceManager.GetString("HasDeniedCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha denegado el acceso a su almacenamiento por favor permita el acceso desde ajustes de su dispositivo.
        /// </summary>
        internal static string HasDeniedStorage {
            get {
                return ResourceManager.GetString("HasDeniedStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo seleccionado es un archivo de texto ¿Calcular la entropia del texto en su lugar?.
        /// </summary>
        internal static string ItsAFileNotAnImage {
            get {
                return ResourceManager.GetString("ItsAFileNotAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo seleccionado es una imagen, ¿Calcular la entropia de esta imagen en su lugar?.
        /// </summary>
        internal static string ItsAnImageNotAFile {
            get {
                return ResourceManager.GetString("ItsAnImageNotAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropia de Shannon.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo seleccionado no es un archivo de texto plano, si continua la lectura puede resultar en resultados inesperados.
        ///¿Continuar?.
        /// </summary>
        internal static string NotPlainTextFile {
            get {
                return ResourceManager.GetString("NotPlainTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar archivo.
        /// </summary>
        internal static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor espere....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomar fotografía.
        /// </summary>
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fundamento teórico.
        /// </summary>
        internal static string Theory {
            get {
                return ResourceManager.GetString("Theory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropia total.
        /// </summary>
        internal static string TotalEntropy {
            get {
                return ResourceManager.GetString("TotalEntropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos....
        /// </summary>
        internal static string WeAreSorry {
            get {
                return ResourceManager.GetString("WeAreSorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
